// <auto-generated />
using System;
using LibraryByORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryByORM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107080212_FixDuplicateStaff")]
    partial class FixDuplicateStaff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryByORM.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("authorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("authorNationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("LibraryByORM.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ISBN")
                        .HasColumnType("int");

                    b.Property<int>("genreId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("publicationYear")
                        .HasColumnType("date");

                    b.Property<int>("publisherId")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("genreId");

                    b.HasIndex("publisherId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryByORM.BookAuthor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("authorId")
                        .HasColumnType("int");

                    b.Property<int>("bookId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("authorId");

                    b.HasIndex("bookId");

                    b.ToTable("BookAuthors");
                });

            modelBuilder.Entity("LibraryByORM.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("LibraryByORM.BranchAddress", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postalCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchAddresses");
                });

            modelBuilder.Entity("LibraryByORM.BranchContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("contactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchContacts");
                });

            modelBuilder.Entity("LibraryByORM.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("LibraryByORM.LibraryMember", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("memberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memberShipStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("LibraryMembers");
                });

            modelBuilder.Entity("LibraryByORM.LibraryStaff", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Staffname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("BranchId");

                    b.ToTable("LibraryStaffs");
                });

            modelBuilder.Entity("LibraryByORM.MemberAddress", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.Property<string>("postalCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("memberId");

                    b.ToTable("MemberAddresses");
                });

            modelBuilder.Entity("LibraryByORM.MemberContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("contactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("memberId");

                    b.ToTable("MemberContacts");
                });

            modelBuilder.Entity("LibraryByORM.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("publisherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("LibraryByORM.PublisherContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("contactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("publisherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("publisherId");

                    b.ToTable("PublisherContacts");
                });

            modelBuilder.Entity("LibraryByORM.StaffContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("contactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("staffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("staffId");

                    b.ToTable("StaffContacts");
                });

            modelBuilder.Entity("LibraryByORM.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("barrowDate")
                        .HasColumnType("date");

                    b.Property<int>("bookId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("dueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("fineAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("returnDate")
                        .HasColumnType("date");

                    b.Property<int>("staffId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("BranchId");

                    b.HasIndex("bookId");

                    b.HasIndex("memberId");

                    b.HasIndex("staffId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("LibraryByORM.Book", b =>
                {
                    b.HasOne("LibraryByORM.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("genreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryByORM.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("publisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LibraryByORM.BookAuthor", b =>
                {
                    b.HasOne("LibraryByORM.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("authorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryByORM.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("bookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryByORM.BranchAddress", b =>
                {
                    b.HasOne("LibraryByORM.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("LibraryByORM.BranchContact", b =>
                {
                    b.HasOne("LibraryByORM.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("LibraryByORM.LibraryStaff", b =>
                {
                    b.HasOne("LibraryByORM.Branch", "Branch")
                        .WithMany("LibraryStaffs")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("LibraryByORM.MemberAddress", b =>
                {
                    b.HasOne("LibraryByORM.LibraryMember", "LibraryMember")
                        .WithMany()
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryMember");
                });

            modelBuilder.Entity("LibraryByORM.MemberContact", b =>
                {
                    b.HasOne("LibraryByORM.LibraryMember", "LibraryMember")
                        .WithMany()
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryMember");
                });

            modelBuilder.Entity("LibraryByORM.PublisherContact", b =>
                {
                    b.HasOne("LibraryByORM.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("publisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LibraryByORM.StaffContact", b =>
                {
                    b.HasOne("LibraryByORM.LibraryStaff", "LibraryStaff")
                        .WithMany()
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryStaff");
                });

            modelBuilder.Entity("LibraryByORM.Transaction", b =>
                {
                    b.HasOne("LibraryByORM.Branch", "Branch")
                        .WithMany("Transactions")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryByORM.Book", "Book")
                        .WithMany("Transactions")
                        .HasForeignKey("bookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryByORM.LibraryMember", "LibraryMember")
                        .WithMany("Transactions")
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryByORM.LibraryStaff", "LibraryStaff")
                        .WithMany("Transactions")
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Branch");

                    b.Navigation("LibraryMember");

                    b.Navigation("LibraryStaff");
                });

            modelBuilder.Entity("LibraryByORM.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("LibraryByORM.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LibraryByORM.Branch", b =>
                {
                    b.Navigation("LibraryStaffs");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LibraryByORM.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryByORM.LibraryMember", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LibraryByORM.LibraryStaff", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LibraryByORM.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
